### ISSUE TITLE
TypeError: unhashable type:list.

### ISSUE THREAD

**Issue by kobykotiv** [sunshineatnoon/PytorchWCT#12]
`Traceback (most recent call last):
  File "WCT.py", line 48, in <module>
    wct = WCT(args)
  File "T:\__ML\PyTorch_UNiversal_Style_Transfer\util.py", line 20, in __init__
    vgg1 = load_lua(args.vgg1)
  File "C:\Users\Zekodon\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 608, in load_lua
    return reader.read()
  File "C:\Users\Zekodon\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 593, in read
    return self.read_object()
  File "C:\Users\Zekodon\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "C:\Users\Zekodon\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 546, in read_object
    return reader_registry[cls_name](self, version)
  File "C:\Users\Zekodon\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 243, in read_nn_class
    attributes = reader.read()
  File "C:\Users\Zekodon\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 595, in read
    return self.read_table()
  File "C:\Users\Zekodon\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "C:\Users\Zekodon\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 571, in read_table
    k = self.read()
  File "C:\Users\Zekodon\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 595, in read
    return self.read_table()
  File "C:\Users\Zekodon\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "C:\Users\Zekodon\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 572, in read_table
    v = self.read()
  File "C:\Users\Zekodon\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 593, in read
    return self.read_object()
  File "C:\Users\Zekodon\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "C:\Users\Zekodon\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 546, in read_object
    return reader_registry[cls_name](self, version)
  File "C:\Users\Zekodon\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 318, in wrapper
    obj = build_fn(reader, version)
  File "C:\Users\Zekodon\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 318, in wrapper
    obj = build_fn(reader, version)
  File "C:\Users\Zekodon\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 243, in read_nn_class
    attributes = reader.read()
  File "C:\Users\Zekodon\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 595, in read
    return self.read_table()
  File "C:\Users\Zekodon\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "C:\Users\Zekodon\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 573, in read_table
    table[k] = v
TypeError: unhashable type: 'list'`

I'm running this one Windows 10 with Anaconda 3.6

**Comment by sunshineatnoon** [comment]
Closed, feel free to reopen if the issue still exists.
